version: '3.7'

services:
  connector:
    image: cesarbr/knot-fog-connector:KNoTU-v3.2.1-rc05
    env_file: './env.d/knot-connector.env'
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: 3
